from flask import render_template, redirect, flash, request
from app import app
from forms import LoginForm, ProfileForm, RecLoginForm, ShortanswerForm, RecommendationsForm, TechskillsForm, RecommendApplicantForm, ChecklistForm
from emails import recommendation_request

applicant = {'email':'aliya@codeforprogress.org','firstname':'Aliya','lastname':'Rahman','password':'P@ssw0rd123','phone': '513-827-8299','address': '4141 Elbern Ave','city': 'Columbus','state': 'OH','zipcode': '43213'}
recommender =  {'email':'aliya@codeforprogress.org','firstname':'Someone','lastname':'Else','password':'autogenerated'}

@app.route('/')
@app.route('/index')
@app.route('/home')
def index():
	return render_template("index.html")

@app.route('/login', methods = ['GET', 'POST'])
def login():
	form = LoginForm()
	if form.validate_on_submit():
		flash('Welcome, ' + form.username.data + '.')
		return redirect('/index')
	return render_template('login.html',
		form=form)
		
@app.route('/checklist', methods = ['GET', 'POST'])
def checklist():
	form = ChecklistForm()
	if form.validate_on_submit():
		return redirect('/createprofile')
	return render_template('checklist.html',
		form=form)

@app.route('/createprofile', methods = ['GET', 'POST'])
def createprofile():
	form = ProfileForm()
	if form.validate_on_submit():
		flash('Congratulations, you just created an account!')
		return redirect('/index')
	return render_template('firstdemographic.html',
		form=form)

@app.route('/demographic', methods = ['GET', 'POST'])
def demographic():
	form = ProfileForm()
	if form.validate_on_submit():
		flash("We've updated your profile.")
		return redirect('/demographic')
	return render_template('demographic.html',
		form=form)

@app.route('/shortanswers', methods = ['GET', 'POST'])
def shortanswers():
	form = ShortanswerForm()
	if form.validate_on_submit():
		flash("Thanks, we've saved your responses to the short answer section.")
		return redirect('/index')
	return render_template('shortanswers.html',
		form=form)

@app.route('/techskills', methods = ['GET', 'POST'])
def techskills():
	form = TechskillsForm()
	if form.validate_on_submit():
		flash("Thanks, we've saved your responses to the tech survey.")
		return redirect('/index')
	return render_template('techskills.html',
		form=form)

@app.route('/recommendations', methods = ['GET', 'POST'])
def recommendations():
	form = RecommendationsForm()
	if form.validate_on_submit():
		flash('Your recommendation info has been saved.')
		return redirect('/index')
	return render_template('recommendations.html',
		form=form)

@app.route('/finalsubmission')
def finalsubmission():
        return render_template("finalsubmission.html")

@app.route('/help')
def help():
        return render_template("help.html")

@app.route('/received')
def received():
#	def email_recommender():
		#email to notify recommenders that they have been asked to provide a recommendation
		#pass in object for current_user (applicant) and object for recommender
#		recommendation_request(recommender, applicant)
		return render_template("received.html")

@app.route('/forgot')
def forgot():
        return render_template("forgot.html")

@app.route('/logout')
def logout():
	return redirect("http://www.codeforprogress.org")

@app.route('/reclogin', methods = ['GET', 'POST'])
def reclogin():
	form = RecLoginForm()
	if form.validate_on_submit():
		flash('Welcome, ' + form.username.data + '.')
		return redirect('/recindex')
	return render_template('reclogin.html',
		form=form)

@app.route('/recindex')
def recindex():
	return render_template("recindex.html")
	
@app.route('/recform', methods = ['GET', 'POST'])
def recform():
	form = RecommendApplicantForm()
	if form.validate_on_submit():
		recommendation_request(recommender, applicant)
		flash('Your recommendation has been recorded.')
		return redirect('/recindex')
	return render_template('recform.html',
		form=form)

@app.route('/finalrecsubmission')
def finalrecsubmission():
	return render_template("finalrecsubmission.html")
	
@app.route('/reclogout')
def reclogout():
	return render_template("reclogin.html")

@app.route('/rechelp')
def rechelp():
        return render_template("rechelp.html")
