"""empty message

Revision ID: 4a8ff5c45658
Revises: None
Create Date: 2014-01-17 10:06:49.503077

"""

# revision identifiers, used by Alembic.
revision = '4a8ff5c45658'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=45), nullable=True),
    sa.Column('password', sa.String(length=45), nullable=True),
    sa.Column('firstname', sa.String(length=45), nullable=True),
    sa.Column('lastname', sa.String(length=45), nullable=True),
    sa.Column('phone', sa.String(length=45), nullable=True),
    sa.Column('address', sa.String(length=90), nullable=True),
    sa.Column('city', sa.String(length=45), nullable=True),
    sa.Column('state', sa.String(length=45), nullable=True),
    sa.Column('zipcode', sa.String(length=10), nullable=True),
    sa.Column('languages', sa.Text(), nullable=True),
    sa.Column('culturalgroups', sa.Text(), nullable=True),
    sa.Column('working', sa.Text(), nullable=True),
    sa.Column('school', sa.Text(), nullable=True),
    sa.Column('appsource', sa.String(length=50), nullable=True),
    sa.Column('Q01', sa.Text(), nullable=True),
    sa.Column('Q02', sa.Text(), nullable=True),
    sa.Column('Q03', sa.Text(), nullable=True),
    sa.Column('Q04', sa.Text(), nullable=True),
    sa.Column('Q05', sa.Text(), nullable=True),
    sa.Column('Q06', sa.Text(), nullable=True),
    sa.Column('Q07', sa.Text(), nullable=True),
    sa.Column('Q08', sa.Text(), nullable=True),
    sa.Column('Q09', sa.Text(), nullable=True),
    sa.Column('Q10', sa.Text(), nullable=True),
    sa.Column('Q11', sa.Text(), nullable=True),
    sa.Column('Q12', sa.Text(), nullable=True),
    sa.Column('basicq1', sa.String(length=45), nullable=True),
    sa.Column('basicq2', sa.String(length=45), nullable=True),
    sa.Column('basicq3', sa.String(length=45), nullable=True),
    sa.Column('basicq4', sa.String(length=45), nullable=True),
    sa.Column('basicq5', sa.String(length=45), nullable=True),
    sa.Column('basicq6', sa.String(length=45), nullable=True),
    sa.Column('basicq7', sa.String(length=45), nullable=True),
    sa.Column('basicq8', sa.String(length=45), nullable=True),
    sa.Column('basicq9', sa.String(length=45), nullable=True),
    sa.Column('systemsq1', sa.String(length=45), nullable=True),
    sa.Column('systemsq2', sa.String(length=45), nullable=True),
    sa.Column('systemsq3', sa.String(length=45), nullable=True),
    sa.Column('systemsq4', sa.String(length=45), nullable=True),
    sa.Column('codingq1', sa.String(length=45), nullable=True),
    sa.Column('codingq2', sa.String(length=45), nullable=True),
    sa.Column('codingq3', sa.String(length=45), nullable=True),
    sa.Column('codingq4', sa.String(length=45), nullable=True),
    sa.Column('codingq5', sa.String(length=45), nullable=True),
    sa.Column('codingq6', sa.String(length=45), nullable=True),
    sa.Column('rec1firstname', sa.String(length=45), nullable=True),
    sa.Column('rec1lastname', sa.String(length=45), nullable=True),
    sa.Column('rec1email', sa.String(length=45), nullable=True),
    sa.Column('rec1phone', sa.String(length=45), nullable=True),
    sa.Column('rec1how', sa.Text(), nullable=True),
    sa.Column('rec2firstname', sa.String(length=45), nullable=True),
    sa.Column('rec2lastname', sa.String(length=45), nullable=True),
    sa.Column('rec2email', sa.String(length=45), nullable=True),
    sa.Column('rec2phone', sa.String(length=45), nullable=True),
    sa.Column('rec2how', sa.Text(), nullable=True),
    sa.Column('rec3firstname', sa.String(length=45), nullable=True),
    sa.Column('rec3lastname', sa.String(length=45), nullable=True),
    sa.Column('rec3email', sa.String(length=45), nullable=True),
    sa.Column('rec3phone', sa.String(length=45), nullable=True),
    sa.Column('rec3how', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('application_complete', sa.Integer(), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.Column('all_recs_complete', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('recommendation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('recommender_id', sa.Integer(), nullable=True),
    sa.Column('recq1', sa.Integer(), nullable=True),
    sa.Column('recq1ex', sa.Text(), nullable=True),
    sa.Column('recq2', sa.Integer(), nullable=True),
    sa.Column('recq2ex', sa.Text(), nullable=True),
    sa.Column('recq3', sa.Integer(), nullable=True),
    sa.Column('recq3ex', sa.Text(), nullable=True),
    sa.Column('recq4', sa.Integer(), nullable=True),
    sa.Column('recq4ex', sa.Text(), nullable=True),
    sa.Column('recq5', sa.Integer(), nullable=True),
    sa.Column('recq5ex', sa.Text(), nullable=True),
    sa.Column('recq6', sa.Integer(), nullable=True),
    sa.Column('recq6ex', sa.Text(), nullable=True),
    sa.Column('recq7', sa.Text(), nullable=True),
    sa.Column('recq8', sa.Text(), nullable=True),
    sa.Column('recommendation_complete', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendation')
    op.drop_table('user')
    ### end Alembic commands ###
