"""empty message

Revision ID: 5184c716cc39
Revises: 4a8ff5c45658
Create Date: 2014-01-19 21:15:00.616613

"""

# revision identifiers, used by Alembic.
revision = '5184c716cc39'
down_revision = '4a8ff5c45658'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluator_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('critical', sa.Integer(), nullable=True),
    sa.Column('mission', sa.Integer(), nullable=True),
    sa.Column('community', sa.Integer(), nullable=True),
    sa.Column('inspire', sa.Integer(), nullable=True),
    sa.Column('yesno', sa.Text(), nullable=True),
    sa.Column('interview', sa.Text(), nullable=True),
    sa.Column('additional', sa.Text(), nullable=True),
    sa.Column('evaluation_complete', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'user', ['email'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user')
    op.drop_table('evaluation')
    ### end Alembic commands ###
