"""empty message

Revision ID: 59fd882bca7e
Revises: 5184c716cc39
Create Date: 2014-01-19 21:37:18.663322

"""

# revision identifiers, used by Alembic.
revision = '59fd882bca7e'
down_revision = '5184c716cc39'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('eval1_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('eval2_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('eval3_id', sa.Integer(), nullable=True))
    op.drop_index('email_2', 'user')
    op.create_unique_constraint(None, 'user', ['email'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user')
    op.create_index('email_2', 'user', [u'email'], unique=True)
    op.drop_column('user', 'eval3_id')
    op.drop_column('user', 'eval2_id')
    op.drop_column('user', 'eval1_id')
    ### end Alembic commands ###
